language: python
python: 2.7
env:
  global:
    MANHOLE_TEST_TIMEOUT=30
  matrix:
    - TOXENV=2.6
    - TOXENV=2.6-eventlet
    - TOXENV=2.6-eventlet-nocover
    - TOXENV=2.6-eventlet-nocover-patchthread
    - TOXENV=2.6-eventlet-patchthread
    - TOXENV=2.6-gevent
    - TOXENV=2.6-gevent-nocover
    - TOXENV=2.6-gevent-nocover-patchthread
    - TOXENV=2.6-gevent-patchthread
    - TOXENV=2.6-nocover
    - TOXENV=2.6-nocover-patchthread
    - TOXENV=2.6-patchthread
    - TOXENV=2.6-signalfd
    - TOXENV=2.6-signalfd-eventlet
    - TOXENV=2.6-signalfd-eventlet-nocover
    - TOXENV=2.6-signalfd-eventlet-nocover-patchthread
    - TOXENV=2.6-signalfd-eventlet-patchthread
    - TOXENV=2.6-signalfd-gevent
    - TOXENV=2.6-signalfd-gevent-nocover
    - TOXENV=2.6-signalfd-gevent-nocover-patchthread
    - TOXENV=2.6-signalfd-gevent-patchthread
    - TOXENV=2.6-signalfd-nocover
    - TOXENV=2.6-signalfd-nocover-patchthread
    - TOXENV=2.6-signalfd-patchthread
    - TOXENV=2.7
    - TOXENV=2.7-eventlet
    - TOXENV=2.7-eventlet-nocover
    - TOXENV=2.7-eventlet-nocover-patchthread
    - TOXENV=2.7-eventlet-patchthread
    - TOXENV=2.7-gevent
    - TOXENV=2.7-gevent-nocover
    - TOXENV=2.7-gevent-nocover-patchthread
    - TOXENV=2.7-gevent-patchthread
    - TOXENV=2.7-nocover
    - TOXENV=2.7-nocover-patchthread
    - TOXENV=2.7-patchthread
    - TOXENV=2.7-signalfd
    - TOXENV=2.7-signalfd-eventlet
    - TOXENV=2.7-signalfd-eventlet-nocover
    - TOXENV=2.7-signalfd-eventlet-nocover-patchthread
    - TOXENV=2.7-signalfd-eventlet-patchthread
    - TOXENV=2.7-signalfd-gevent
    - TOXENV=2.7-signalfd-gevent-nocover
    - TOXENV=2.7-signalfd-gevent-nocover-patchthread
    - TOXENV=2.7-signalfd-gevent-patchthread
    - TOXENV=2.7-signalfd-nocover
    - TOXENV=2.7-signalfd-nocover-patchthread
    - TOXENV=2.7-signalfd-patchthread
    - TOXENV=3.2
    - TOXENV=3.2-eventlet
    - TOXENV=3.2-eventlet-nocover
    - TOXENV=3.2-eventlet-nocover-patchthread
    - TOXENV=3.2-eventlet-patchthread
    - TOXENV=3.2-gevent
    - TOXENV=3.2-gevent-nocover
    - TOXENV=3.2-gevent-nocover-patchthread
    - TOXENV=3.2-gevent-patchthread
    - TOXENV=3.2-nocover
    - TOXENV=3.2-nocover-patchthread
    - TOXENV=3.2-patchthread
    - TOXENV=3.2-signalfd
    - TOXENV=3.2-signalfd-eventlet
    - TOXENV=3.2-signalfd-eventlet-nocover
    - TOXENV=3.2-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.2-signalfd-eventlet-patchthread
    - TOXENV=3.2-signalfd-gevent
    - TOXENV=3.2-signalfd-gevent-nocover
    - TOXENV=3.2-signalfd-gevent-nocover-patchthread
    - TOXENV=3.2-signalfd-gevent-patchthread
    - TOXENV=3.2-signalfd-nocover
    - TOXENV=3.2-signalfd-nocover-patchthread
    - TOXENV=3.2-signalfd-patchthread
    - TOXENV=3.3
    - TOXENV=3.3-eventlet
    - TOXENV=3.3-eventlet-nocover
    - TOXENV=3.3-eventlet-nocover-patchthread
    - TOXENV=3.3-eventlet-patchthread
    - TOXENV=3.3-gevent
    - TOXENV=3.3-gevent-nocover
    - TOXENV=3.3-gevent-nocover-patchthread
    - TOXENV=3.3-gevent-patchthread
    - TOXENV=3.3-nocover
    - TOXENV=3.3-nocover-patchthread
    - TOXENV=3.3-patchthread
    - TOXENV=3.3-signalfd
    - TOXENV=3.3-signalfd-eventlet
    - TOXENV=3.3-signalfd-eventlet-nocover
    - TOXENV=3.3-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.3-signalfd-eventlet-patchthread
    - TOXENV=3.3-signalfd-gevent
    - TOXENV=3.3-signalfd-gevent-nocover
    - TOXENV=3.3-signalfd-gevent-nocover-patchthread
    - TOXENV=3.3-signalfd-gevent-patchthread
    - TOXENV=3.3-signalfd-nocover
    - TOXENV=3.3-signalfd-nocover-patchthread
    - TOXENV=3.3-signalfd-patchthread
    - TOXENV=3.4
    - TOXENV=3.4-eventlet
    - TOXENV=3.4-eventlet-nocover
    - TOXENV=3.4-eventlet-nocover-patchthread
    - TOXENV=3.4-eventlet-patchthread
    - TOXENV=3.4-gevent
    - TOXENV=3.4-gevent-nocover
    - TOXENV=3.4-gevent-nocover-patchthread
    - TOXENV=3.4-gevent-patchthread
    - TOXENV=3.4-nocover
    - TOXENV=3.4-nocover-patchthread
    - TOXENV=3.4-patchthread
    - TOXENV=3.4-signalfd
    - TOXENV=3.4-signalfd-eventlet
    - TOXENV=3.4-signalfd-eventlet-nocover
    - TOXENV=3.4-signalfd-eventlet-nocover-patchthread
    - TOXENV=3.4-signalfd-eventlet-patchthread
    - TOXENV=3.4-signalfd-gevent
    - TOXENV=3.4-signalfd-gevent-nocover
    - TOXENV=3.4-signalfd-gevent-nocover-patchthread
    - TOXENV=3.4-signalfd-gevent-patchthread
    - TOXENV=3.4-signalfd-nocover
    - TOXENV=3.4-signalfd-nocover-patchthread
    - TOXENV=3.4-signalfd-patchthread
    - TOXENV=pypy
    - TOXENV=pypy-eventlet
    - TOXENV=pypy-eventlet-nocover
    - TOXENV=pypy-eventlet-nocover-patchthread
    - TOXENV=pypy-eventlet-patchthread
    - TOXENV=pypy-gevent
    - TOXENV=pypy-gevent-nocover
    - TOXENV=pypy-gevent-nocover-patchthread
    - TOXENV=pypy-gevent-patchthread
    - TOXENV=pypy-nocover
    - TOXENV=pypy-nocover-patchthread
    - TOXENV=pypy-patchthread
    - TOXENV=pypy-signalfd
    - TOXENV=pypy-signalfd-eventlet
    - TOXENV=pypy-signalfd-eventlet-nocover
    - TOXENV=pypy-signalfd-eventlet-nocover-patchthread
    - TOXENV=pypy-signalfd-eventlet-patchthread
    - TOXENV=pypy-signalfd-gevent
    - TOXENV=pypy-signalfd-gevent-nocover
    - TOXENV=pypy-signalfd-gevent-nocover-patchthread
    - TOXENV=pypy-signalfd-gevent-patchthread
    - TOXENV=pypy-signalfd-nocover
    - TOXENV=pypy-signalfd-nocover-patchthread
    - TOXENV=pypy-signalfd-patchthread
before_install:
  - |
    case $TOXENV in
      pypy*)
        deactivate
        sudo apt-add-repository --yes ppa:pypy/ppa
        sudo apt-get update
        sudo apt-get install pypy
        source ~/virtualenv/pypy/bin/activate
      ;;
      3.4*))
        sudo apt-get update
        sudo apt-get install python3.4-dev
        source ~/virtualenv/python3.4
        virtualenv ~/virtualenv/python3.4 --python=$(which python3.4)
        source ~/virtualenv/python3.4/bin/activate
      ;;
    esac
    python --version
    uname -a
    lsb_release -a 
install:
  - pip install tox
script:
  - tox -v
after_success:
  - |
    if [[ $WITH_COVERAGE == yes ]]; then
      .tox/$TOXENV/bin/coverage combine
      .tox/$TOXENV/bin/coverage report
      .tox/$TOXENV/bin/coveralls
    fi
notifications:
  email:
    on_success: never
    on_failure: always